### ISSUE TITLE
Question: Does this work for .NET Core 3.0?

### ISSUE THREAD

**Issue by mattfrear** [bruno-garcia/Bazinga.AspNetCore.Authentication.Basic#12]
Hi
I've been using this library in my ASP.NET Core 2.2 application and it works great.
I've just upgraded the application to .NET Core 3.0, and I think it doesn't work any more? But it could be me...

i.e. my `Authenticate(string username, string password)` method is never called while debugging.

**Comment by bruno-garcia** [comment]
I'm not using this library anymore in any project so it hasn't affected me yet.
Do you mind providing a repro so I can debug through?

I started this PR #11 before ASP.NET Core 3 was released but it was more focused on the nullable ref types.

**Comment by mattfrear** [comment]
Hi Bruno
I had another go at upgrading my app to .NET Core (this time 3.1) and it seems to work fine this time.

Thanks.

**Comment by bruno-garcia** [comment]
That's great news. Thanks @mattfrear
