### ISSUE TITLE
Update to instructions: Need to add app.UseAuthorization() code line as well

### ISSUE THREAD

**Issue by levitation** [bruno-garcia/Bazinga.AspNetCore.Authentication.Basic#13]
Update to the readme: You need to add `app.UseAuthorization();` after `app.UseAuthentication();` as well, so you will end up with the following code: 
```
app.UseAuthentication(); 
app.UseAuthorization();
```

**Comment by bruno-garcia** [comment]
Thanks for raising.

Solved through: https://github.com/bruno-garcia/Bazinga.AspNetCore.Authentication.Basic/commit/775ea1eaa0459455c76d7430a65c78624c2eedd7
