### ISSUE TITLE
Allow for more complex Principal/Identity construction.

### ISSUE THREAD

**Issue by marcrocny** [bruno-garcia/Bazinga.AspNetCore.Authentication.Basic#2]
The extension only allows for a `bool` response and automatically fills in a contextual `ClaimsPrincipal/CliamsIdentity` with just the username. There's no way (that I can see) to provide an extension to the claims included there without fully overriding `BasicAuthenticationHandler.HandleAuthenticateAsync()` which kind of obviates the purpose of the class.

Note also, for what it's worth: while I like (maybe prefer) the "direct injection" method used here, the more "aspnetcore-correct" way of doing this would appear to be adding the injected authentication method to an "*AuthenticationEvents" object that is configured either directly on `AuthenticationSchemeOptions.Events` or indirectly by setting the type on `AuthenticationSchemeOptions.EventsType`. The latter uses dependency injection to create the events-object anyway, but there you are.

**Comment by bruno-garcia** [comment]
Hi @marcrocny, thanks for your feedback!
Looking at the Microsoft [implementation for Twitter, for example](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs#L47), I don't see them invoking anything on the Events giving a chance to the application to add more claims to the ClaimsIdentity. It sets the 4 predefined claim types with values returning from 'ObtainAccessTokenAsync' call but that's it. Perhaps I'm missing something?

I wasn't aware of the EventsType hook when I wrote this. Perhaps it could use this API instead to be closer to the other Microsoft written handlers. 
What would you suggest?

**Comment by bruno-garcia** [comment]
I took a look at the code and it does [calls into `Events` with the newly created ClaimsPrincipal](https://github.com/bruno-garcia/Bazinga.AspNetCore.Authentication.Basic/blob/master/src/BasicAuthenticationHandler.cs#L85).

That's the hook for the application to modify it or even reject the user by calling `AuthenticationSucceededContext.Fail` during `CredentialsValidated`

**Comment by bruno-garcia** [comment]
@marcrocny I'll close the issue for now. Feel free to reopen if my last comment doesn't solve your problem.

**Comment by springy76** [comment]
I also needed to persist some additional claims which I get during DB lookup, so I slightly modified the code:
[my commit](https://github.com/springy76/Bazinga.AspNetCore.Authentication.Basic/commit/2d5ead99573b464a0d988d1d40d223d4a8f64444)

**Comment by bruno-garcia** [comment]
I'd be happy to merge a pull request with your changes.

Although I'm not a big fan of passing a mutating collection like that, I see it solves the problem rather simply. And changing to code now to abandon the original idea of the generic argument for registration in favor of the _EventsType_ approach is not really worth it as it'll break everyone using this for little value.
