### ISSUE TITLE
MissingMethodException at runtime

### ISSUE THREAD

**Issue by springy76** [bruno-garcia/Bazinga.AspNetCore.Authentication.Basic#3]
My debugger doesn't reach the entire `Startup.ConfigureServices` method at all, runtime throws `MissingMethodException` while trying to JIT it.

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Microsoft.AspNetCore.Authentication.AuthenticationBuilder Microsoft.Extensions.DependencyInjection.BasicAuthenticationExtensions.AddBasicAuthentication(Microsoft.AspNetCore.Authentication.AuthenticationBuilder, System.Func`2<System.ValueTuple`2<System.String,System.String>,System.Threading.Tasks.Task`1<Boolean>>)'.
  Source=AspNetCoreWebApplication_API
  StackTrace:
   at AspNetCoreWebApplication_API.Startup.ConfigureServices(IServiceCollection services) in MyCode
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at AspNetCoreWebApplication_API.Program.BuildWebHost(Int32 port) in MyCode
```

The only line I added was this one: `authBuilder.AddBasicAuthentication(tuple => Task.FromResult(true));`

@Microsoft Thank you Microsoft for trading strong references which fail at compile time against soft references which just can fail any time any where.

**Comment by bruno-garcia** [comment]
Could you please describe your environment a little bit? 
What kind of system is this running? net47 or netcoreapp2.0, on Windows or Linux and which version.

Could you also describe how are you starting the app (e.g: dotnet /path/to/App.dll) and also verify if the DLL brought in by the NuGet package (Bazinga.AspNetCore.Authentication.Basic.dll) is at your deployment directory? Perhaps it wasn't included during your build packaging.

With a bit more input we can try to narrow down the issue.

**Comment by springy76** [comment]
I'm targetting net46x. I meanwhile switched from NuGet package to full source but still same problem, even after consolidating versions of referenced NuGet packages.

Switching to net471 removes the problem.

Manually referencing System.ValueTuple 4.4.0 (against net461) does NOT remove the problem.

The output directory seems to contain all DLLs. Any idea for narrowing this down?
It's not a show-stopper since I could use net471. But I personally hate it when I don't understand it, and I have another project (not older than a few months) which just cannot be migrated from net462 to net471 without breaking everything related to System.Net.Http.

**Comment by bruno-garcia** [comment]
This project is packaged as a _netstandard2.0_ library so [it should be supported by net461](https://docs.microsoft.com/en-us/dotnet/standard/net-standard). 

Is it possible to provide a repro? A small repository where I could reproduce locally and try to identify the problem?

**Comment by springy76** [comment]
I wish I could reproduce. The original project already only was a slightly modified original WebApi template. But a completely new project doesn't show this problem -- though on a different computer.

**Comment by springy76** [comment]
I can't reproduce on the other computer either. Maybe it's because I installed this 4.7.1 update on both PCs this week:
[Applications targeting .NET 4.6.1 that use .NET Standard libraries might be broken when running on .NET 4.7.1](https://github.com/Microsoft/dotnet/blob/master/releases/net471/KnownIssues/510901-BCL%20Apps%20targeting%20.NET-4.6.1%20that%20use%20.NET%20Standard%20libraries%20might%20be%20broken%20when%20running%20on%20.NET%204.7.1.md)

**Comment by bruno-garcia** [comment]
That explains. Glad the problem is gone.
