### ISSUE TITLE
No authenticationScheme was specified, and there was no DefaultChallengeScheme found

### ISSUE THREAD

**Issue by JoostvdB94** [bruno-garcia/Bazinga.AspNetCore.Authentication.Basic#4]
Hello,

First of all, thanks for your Basic Authentication nuget package.

There is a problem that occurs when using the latest NuGet package:
When using the following code
```csharp
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddAuthentication()
                .AddBasicAuthentication(c => ValidateUserCredentials(c.username, c.password));
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseAuthentication();
            app.UseMvc();
        }
```

When trying to log in using basic authentication, I get this error:
`No authenticationScheme was specified, and there was no DefaultChallengeScheme found`

I could not find out why it's throwing this error, and the code is set up according to the code examples provided in the `README.md` 

Could you please check the documentation on any errors or missing configuration? 

Thanks in advance

**Comment by bruno-garcia** [comment]
The sample on readme is missing explicitly setting the scheme.

Please define also the scheme, like:

```csharp
services.AddAuthentication(BasicAuthenticationDefaults.AuthenticationScheme)
    .AddBasicAuthentication(c => ValidateUserCredentials(c.username, c.password));
```

If you are migrating from 1.x, it's worth checking [ASP.NET Docs](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x)

I'll update the README.md

**Comment by JoostvdB94** [comment]
Thanks!

**Comment by bruno-garcia** [comment]
README updated. Thanks for letting me know.
