### ISSUE TITLE
How can I add my own claim types?

### ISSUE THREAD

**Issue by lira92** [bruno-garcia/Bazinga.AspNetCore.Authentication.Basic#5]
I need to add some claim types in identity after the user has been authenticated. Can I do this?

**Comment by bruno-garcia** [comment]
The library [calls into `Events` with the newly created ClaimsPrincipal](https://github.com/bruno-garcia/Bazinga.AspNetCore.Authentication.Basic/blob/master/src/BasicAuthenticationHandler.cs#L85).

That's the hook for the application to modify it or even reject the user by calling `AuthenticationSucceededContext.Fail` during `CredentialsValidated`. 

You can modify the `Principal` property with a new instance if needed.

**Comment by lira92** [comment]
thanks for your help @bruno-garcia, it worked to me. Do you think that is interesting to include an example to implement this in your readme? I can provide a PR for this.

**Comment by bruno-garcia** [comment]
Sure! That'd be great, thank you.

**Comment by bruno-garcia** [comment]
Done #6
