### ISSUE TITLE
Authentication failures ignored

### ISSUE THREAD

**Issue by brobichaud** [bruno-garcia/Bazinga.AspNetCore.Authentication.Basic#7]
Hi, Thanks a bunch for this nuget!

I'm trying to integrate and my IBasicCredentialVerifier:Authenticate() method is being called, but when I return Task.FromResult(false); the method call still succeeds as if no authentication was checked. I've added this after services.AddMvc():

```
      services.AddAuthentication(BasicAuthenticationDefaults.AuthenticationScheme)
            .AddBasicAuthentication<AuthenticationBasic>();
```

And this just before app.UseMvc():

```
      app.UseAuthentication();
```

Am I missing a step?
I also notice that if I call a method without the Authorization header then no authentication is attempted.

Finally, I have a couple of fixes for the readme.md that I'd like to create a pull request for.

**Comment by bruno-garcia** [comment]
Hi @brobichaud,

Would it be possible to provide a small reproducible example?
I'd be glad to fix it but I can't reproduce it.

> Finally, I have a couple of fixes for the readme.md that I'd like to create a pull request for.
I'm more than happy to merge in any improvements! Thanks!

**Comment by brobichaud** [comment]
Attached is a default Api webapp created from VS2017 with only the changes being those needed to enable basicauth. I see the same two problems in this app:

1. If no Authorization header is passed (or one without the Basicauth signature) then the request is not authenticated, and thus bypasses security altogether
2. If a basicauth Authorization header is passed then my IBasicCredentialVerifier is called but a false return value seems to have no effect, the method still runs to completion.

Note that I am using DotNet Core 2.1.

[basicauth.zip](https://github.com/bruno-garcia/Bazinga.AspNetCore.Authentication.Basic/files/2171470/basicauth.zip)

**Comment by bruno-garcia** [comment]
Hi @brobichaud,

Your controller doesn't not require authentication. It doesn't have `[Authorize]` nor MVC is configured to require authentication to all requests so the controller gets hit without challenging the user.

I've added `[Authorize]` to your controller and it worked properly.
Could you give that a try?

**Comment by brobichaud** [comment]
@bruno-garcia ack! I can't believe I made such a stupid mistake. Yeah that totally fixed it. Consider it a DotNet Core newbie mistake. I had assumed everything I needed to add was in the readme and never even thought of this.

Thanks a bunch for the help.

**Comment by bruno-garcia** [comment]
No worries. I guess it would be worth mentioning that on the README too.
Can't just assume people will know that.
